name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  source-paths:
    description: 'source paths'
    required: true
    default: 'src'

  test-paths:
    description: 'test paths'
    required: true
    default: 'test'

  test-file-pattern:
    description: 'test paths'
    required: true
    default: '_test.clj$'

outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-paths }}
    - ${{ inputs.test-patsh }}
    - ${{ inputs.test-file-pattern }}
