name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  classpath:
    description: 'classpath'
    required: true
    default: 'src:test'
  namespaces:
    description: 'namespaces'
    required: true
    default: ''
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.classpath }}
    - ${{ inputs.namespaces }}
