version: '3'
services:
  local-sqs:
    container_name: test-local-sqs
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"
      - "9325:9325"
    # volumes:
    #   - "./elasticmq.conf:/opt/elasticmq.conf"
