name: Tag and Release

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      release:
        description: 'True to release'
        required: true
        type: boolean

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.email "liquidz.uo@gmail.com"
          git config user.name ${{ github.actor }}
          git restore .
          bash foo.sh
          git commit -a -m "test [skip ci]"
          git push origin master
          git fetch origin dummy
          git switch dummy
          git rebase master
          bash foo.sh
          git commit -a -m "after test [skip ci]"
          git push origin dummy
