name: Tag and Release

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      release:
        description: 'True to release'
        required: true
        type: boolean

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Show versions
        run: |
          java -version
          clojure --version

      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: test-m2-${{ hashFiles('deps.edn') }}-v1

      - name: Lint build.edn
        run: clojure -T:build lint

      - id: tag
        run: |
          clojure -T:build update-documents
          git diff
          git config --global user.email "github-actions@example.com"
          git config --global user.name "github-actions"
          git add -A
          git commit -m "Update for release" || exit 0
          git push

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.version }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
