name: test1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo hello
      # - name: my action test
      #   uses: ./
      #   with:
      #     classpath: 'src test'
      #     namespaces: 'foo.core-test'
      #
  gh-page-test:
    runs-on: ubuntu-latest
    steps:
      - name: gh-pages deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
