name: test1
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello=world" >> $GITHUB_ENV

  next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "next answer: ${{ jobs.build.env.hello }}"
