name: test1
on: push
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #        TAG_NAME=$(echo "refs/tags/1.2.3" | sed 's!refs/tags/!!')
  #        echo "tag_name: ${TAG_NAME}"

  build:
    strategy:
      matrix:
        java: ['8', '11', '15']

    runs-on: ubuntu-latest
    # container:
    #   image: clojure:openjdk-15-tools-deps-1.10.1.739
    steps:
      - uses: actions/checkout@v2
      - run: java -version
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@e73bf2b
        with:
          tools-deps: '1.10.1.727'
      - run: which clojure
      - run: which make
      - run: clojure -M:run

  # gh-page-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: gh-pages deploy
  #       uses: peaceiris/actions-gh-pages@v3.6.1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./public
