name: test1
on: push
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #        TAG_NAME=$(echo "refs/tags/1.2.3" | sed 's!refs/tags/!!')
  #        echo "tag_name: ${TAG_NAME}"

  build:
    # strategy:
    #   matrix:
    #     java: [8, 15]

    runs-on: ubuntu-latest
    # services:
    #   local-sqs:
    #     image: softwaremill/elasticmq-native
    #     ports:
    #       - 9324:9324
    #     volumes:
    #       - ${{ github.workspace }}/dev-docker:/opt

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: docker up
        run: cd dev-docker && docker compose up -d

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'


      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - run: clojure -M:dev:test
      # - name: Use Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      # - name: Maven cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.m2
      #     key: maven-${{ hashFiles('shadow-cljs.edn') }}
      #     restore-keys: maven-
      # - name: NPM cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: npm-${{ hashFiles('package-lock.json') }}
      #     restore-keys: npm-
      # - run: npm install
      # - run: make shadow-test
      # - run: echo '::error file=deps.edn::foo\nbar\tbaz'
      # - run: echo '::group::hello'
      # - run: echo 'plain text1'
      # - run: echo '::error file=deps.edn::in group??'
      # - run: echo '::error file=deps.edn::in group!!??'
      # - run: echo 'plain text2'
      # - run: echo '::endgroup::'
      # - run: java -version
      # # - uses: actions/setup-java@v1
      # #   with:
      # #     java-version: '${{ matrix.java }}'
      # # - run: java -version
      # - uses: DeLaGuardo/setup-clojure@e73bf2b
      #   with:
      #     tools-deps: '1.10.1.727'
      # - run: whoami
      # - run: echo $HOME
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.m2
      #     key: test-m2-${{ hashFiles('deps.edn') }}-v1
      # - run: clojure -M:run

  # gh-page-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: gh-pages deploy
  #       uses: peaceiris/actions-gh-pages@v3.6.1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./public
