name: test1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $PATH
      - run: |
          ./installer/cljstyle.sh
          mkdir bin
          mv cljstyle bin
      - name: foo
        env:
          PATH: ${{ env.PATH }}:./bin
        run: |
          echo $PATH
          cljstyle --help
