name: test1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         TAG_NAME=$(echo "refs/tags/1.2.3" | sed 's!refs/tags/!!')
         echo "tag_name: ${TAG_NAME}"

  # build:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: clojure:openjdk-11-lein
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: lein run
  #     - run: whoami
  #     - run: ls -al /root
  #     - run: ls -al /root/.m2/repository
  #     - run: cd ~ && pwd

  # gh-page-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: gh-pages deploy
  #       uses: peaceiris/actions-gh-pages@v3.6.1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./public
