name: test1
on:
  push:
    branches:
      - master
      - dev
jobs:
  always:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{github.ref}}

  build_for_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo devdev

  build_for_master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    - run: mkdir public
    - run: cp -pf README.md public/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public


