name: test1
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.foo.outputs.oni2 }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - run: echo "$GITHUB_OUTPUT"
      - run: make test
      # - id: foo
      #   run: sh foo.sh $GITHUB_OUTPUT
# echo "oni=wani" >> $GITHUB_OUTPUT

  # next:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - run: echo "answer = ${{ needs.build.outputs.foo }}"
