name: test1
on:
  pull_request:
    #branches:
    #  - master
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - run: echo 'OK'
