name: test1
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "hello=world" >> $GITHUB_ENV
      - run: echo "answer = ${{ env.hello }}"
