name: test1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clojure
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.1.727.sh
          chmod +x linux-install-1.10.1.727.sh
          sudo ./linux-install-1.10.1.727.sh
      - uses: actions/cache@v2
        with:
          path: /root/.m2
          key: test-m2-${{ hashFiles('deps.edn') }}-v1
      - run: clojure -M:run

  # build:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: clojure:openjdk-11-lein
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: lein run
  #     - run: whoami
  #     - run: ls -al /root
  #     - run: ls -al /root/.m2/repository
  #     - run: cd ~ && pwd

  # gh-page-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: gh-pages deploy
  #       uses: peaceiris/actions-gh-pages@v3.6.1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./public
