name: test1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v3
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0
          ref: master
      - run: |
          git config user.email "liquidz.uo@gmail.com"
          git config user.name ${{ github.actor }}
          git restore .
          bash foo.sh
          git commit -a -m "test [skip ci]"
          git push origin master
          git log -1 --format='%H'
          git fetch origin dummy2
          git switch dummy2
          git log -1 --format='%H'
          git rebase master
          bash foo.sh
          git commit -a -m "after test [skip ci]"
          git push origin dummy2
