name: test1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $PATH
      - run: |
          ./installer/cljstyle
          mv cljstyle /usr/local/bin
      - run: which cljstyle
