name: test2

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please input any text for confirmation'
        required: true

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
      - run: echo "hello world"

