name: test2
on: [push]
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

  build_test2:
    needs: build_test1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
