name: test1
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please input any text for confirmation'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'OK?'
