name: test1
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.foo.outputs.oni }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello=world" >> $GITHUB_ENV
      - run: echo "neko=inu" >> $GITHUB_ENV
      - run: echo "answer = ${{ env.neko }}"
      - id: foo
        run: echo "oni=wani" >> $GITHUB_OUTPUT

  next:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - run: echo "answer = ${{ needs.build.outputs.foo }}"
